name: Clean Jupyter Notebook Outputs for PRs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'notebooks/**/*.ipynb'

jobs:
  clean-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Clean Jupyter Notebook Outputs
        run: |
          set -x  # Enable debugging

          # Fetch the branches first to ensure they exist.
          git fetch origin master:master
          git fetch origin develop:develop

          # Get the list of notebooks changed between master and develop.
          NOTEBOOKS=$(git diff --name-only master develop | grep "notebooks/.*.ipynb$")

          # If there are no notebooks to process, exit.
          if [ -z "$NOTEBOOKS" ]; then
            echo "No notebooks were found for processing."
            exit 0
          fi

          echo "Notebooks to process: $NOTEBOOKS"

          # For each notebook, clear the output.
          for NOTEBOOK in $NOTEBOOKS; do
              if [ -f "$NOTEBOOK" ]; then
                  jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True --inplace "$NOTEBOOK"
                  git add "$NOTEBOOK"
              else
                  echo "Warning: Expected notebook file $NOTEBOOK does not exist."
              fi
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Clean Jupyter Notebook Outputs" -a || echo "No changes to commit"

      - name: Push changes back to PR branch
        run: git push origin ${{ github.head_ref }}
