name: Clean Jupyter Notebook Outputs for PRs to Master

on:
  pull_request:
    branches:
      - master
    paths:
      - 'notebooks/**/*.ipynb'

jobs:
  clean-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Clean Jupyter Notebook Outputs
        run: |
          NOTEBOOKS=$(git diff --name-only HEAD~1 HEAD | grep "notebooks/.*.ipynb$")
          for NOTEBOOK in $NOTEBOOKS; do
              jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True --inplace "$NOTEBOOK"
              git add "$NOTEBOOK"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Clean Jupyter Notebook Outputs" -a || echo "No changes to commit"

      - name: Push changes back to PR branch
        run: git push origin ${{ github.head_ref }}
